/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import sigma.dbgen.tables.CatalogoProductos;
import sigma.dbgen.tables.records.CatalogoProductosRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogoProductosDao extends DAOImpl<CatalogoProductosRecord, sigma.dbgen.tables.pojos.CatalogoProductos, Integer> {

	/**
	 * Create a new CatalogoProductosDao without any configuration
	 */
	public CatalogoProductosDao() {
		super(CatalogoProductos.CATALOGO_PRODUCTOS, sigma.dbgen.tables.pojos.CatalogoProductos.class);
	}

	/**
	 * Create a new CatalogoProductosDao with an attached configuration
	 */
	public CatalogoProductosDao(Configuration configuration) {
		super(CatalogoProductos.CATALOGO_PRODUCTOS, sigma.dbgen.tables.pojos.CatalogoProductos.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(sigma.dbgen.tables.pojos.CatalogoProductos object) {
		return object.getIdProducto();
	}

	/**
	 * Fetch records that have <code>descripcion IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByDescripcion(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.DESCRIPCION, values);
	}

	/**
	 * Fetch records that have <code>desviacion IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByDesviacion(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.DESVIACION, values);
	}

	/**
	 * Fetch records that have <code>existencia IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByExistencia(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.EXISTENCIA, values);
	}

	/**
	 * Fetch records that have <code>fecha_sync IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByFechaSync(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.FECHA_SYNC, values);
	}

	/**
	 * Fetch records that have <code>id_categoria IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByIdCategoria(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.ID_CATEGORIA, values);
	}

	/**
	 * Fetch records that have <code>id_marca IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByIdMarca(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.ID_MARCA, values);
	}

	/**
	 * Fetch records that have <code>id_producto IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByIdProducto(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.ID_PRODUCTO, values);
	}

	/**
	 * Fetch a unique record that has <code>id_producto = value</code>
	 */
	public sigma.dbgen.tables.pojos.CatalogoProductos fetchOneByIdProducto(Integer value) {
		return fetchOne(CatalogoProductos.CATALOGO_PRODUCTOS.ID_PRODUCTO, value);
	}

	/**
	 * Fetch records that have <code>id_tipo_producto IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByIdTipoProducto(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.ID_TIPO_PRODUCTO, values);
	}

	/**
	 * Fetch records that have <code>id_unidad IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByIdUnidad(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.ID_UNIDAD, values);
	}

	/**
	 * Fetch records that have <code>minimo IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByMinimo(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.MINIMO, values);
	}

	/**
	 * Fetch records that have <code>precio_compra IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByPrecioCompra(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.PRECIO_COMPRA, values);
	}

	/**
	 * Fetch records that have <code>precio_venta IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByPrecioVenta(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.PRECIO_VENTA, values);
	}

	/**
	 * Fetch records that have <code>precio_venta_mayoreo IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByPrecioVentaMayoreo(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.PRECIO_VENTA_MAYOREO, values);
	}

	/**
	 * Fetch records that have <code>promedio IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByPromedio(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.PROMEDIO, values);
	}

	/**
	 * Fetch records that have <code>sku IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchBySku(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.SKU, values);
	}

	/**
	 * Fetch records that have <code>sugerido IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchBySugerido(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.SUGERIDO, values);
	}

	/**
	 * Fetch records that have <code>sync IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchBySync(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.SYNC, values);
	}

	/**
	 * Fetch records that have <code>techo IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByTecho(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.TECHO, values);
	}

	/**
	 * Fetch records that have <code>total_ventas IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByTotalVentas(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.TOTAL_VENTAS, values);
	}

	/**
	 * Fetch records that have <code>db_state IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByDbState(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.DB_STATE, values);
	}

	/**
	 * Fetch records that have <code>image_preview IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByImagePreview(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.IMAGE_PREVIEW, values);
	}

	/**
	 * Fetch records that have <code>logo IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByLogo(String... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.LOGO, values);
	}

	/**
	 * Fetch records that have <code>custom IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.CatalogoProductos> fetchByCustom(Integer... values) {
		return fetch(CatalogoProductos.CATALOGO_PRODUCTOS.CUSTOM, values);
	}
}
