/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import sigma.dbgen.tables.TransaccionDetalle;
import sigma.dbgen.tables.records.TransaccionDetalleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionDetalleDao extends DAOImpl<TransaccionDetalleRecord, sigma.dbgen.tables.pojos.TransaccionDetalle, Integer> {

	/**
	 * Create a new TransaccionDetalleDao without any configuration
	 */
	public TransaccionDetalleDao() {
		super(TransaccionDetalle.TRANSACCION_DETALLE, sigma.dbgen.tables.pojos.TransaccionDetalle.class);
	}

	/**
	 * Create a new TransaccionDetalleDao with an attached configuration
	 */
	public TransaccionDetalleDao(Configuration configuration) {
		super(TransaccionDetalle.TRANSACCION_DETALLE, sigma.dbgen.tables.pojos.TransaccionDetalle.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(sigma.dbgen.tables.pojos.TransaccionDetalle object) {
		return object.getIdVentaDetalle();
	}

	/**
	 * Fetch records that have <code>autorizacion_pt IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByAutorizacionPt(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.AUTORIZACION_PT, values);
	}

	/**
	 * Fetch records that have <code>cantidad IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByCantidad(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.CANTIDAD, values);
	}

	/**
	 * Fetch records that have <code>cantidad_promo IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByCantidadPromo(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.CANTIDAD_PROMO, values);
	}

	/**
	 * Fetch records that have <code>descuento IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByDescuento(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.DESCUENTO, values);
	}

	/**
	 * Fetch records that have <code>fecha_actualizacion IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByFechaActualizacion(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.FECHA_ACTUALIZACION, values);
	}

	/**
	 * Fetch records that have <code>id_campana IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByIdCampana(Integer... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.ID_CAMPANA, values);
	}

	/**
	 * Fetch records that have <code>id_producto IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByIdProducto(Integer... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.ID_PRODUCTO, values);
	}

	/**
	 * Fetch records that have <code>id_venta IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByIdVenta(Integer... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA, values);
	}

	/**
	 * Fetch records that have <code>id_venta_detalle IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByIdVentaDetalle(Integer... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA_DETALLE, values);
	}

	/**
	 * Fetch a unique record that has <code>id_venta_detalle = value</code>
	 */
	public sigma.dbgen.tables.pojos.TransaccionDetalle fetchOneByIdVentaDetalle(Integer value) {
		return fetchOne(TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA_DETALLE, value);
	}

	/**
	 * Fetch records that have <code>importe_compra IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByImporteCompra(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.IMPORTE_COMPRA, values);
	}

	/**
	 * Fetch records that have <code>importe_venta IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByImporteVenta(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.IMPORTE_VENTA, values);
	}

	/**
	 * Fetch records that have <code>is_premio IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByIsPremio(Integer... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.IS_PREMIO, values);
	}

	/**
	 * Fetch records that have <code>referencia IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchByReferencia(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.REFERENCIA, values);
	}

	/**
	 * Fetch records that have <code>sobre_cargo IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.TransaccionDetalle> fetchBySobreCargo(String... values) {
		return fetch(TransaccionDetalle.TRANSACCION_DETALLE.SOBRE_CARGO, values);
	}
}
