/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import sigma.dbgen.tables.Transacciones;
import sigma.dbgen.tables.records.TransaccionesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionesDao extends DAOImpl<TransaccionesRecord, sigma.dbgen.tables.pojos.Transacciones, Integer> {

	/**
	 * Create a new TransaccionesDao without any configuration
	 */
	public TransaccionesDao() {
		super(Transacciones.TRANSACCIONES, sigma.dbgen.tables.pojos.Transacciones.class);
	}

	/**
	 * Create a new TransaccionesDao with an attached configuration
	 */
	public TransaccionesDao(Configuration configuration) {
		super(Transacciones.TRANSACCIONES, sigma.dbgen.tables.pojos.Transacciones.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(sigma.dbgen.tables.pojos.Transacciones object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchById(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public sigma.dbgen.tables.pojos.Transacciones fetchOneById(Integer value) {
		return fetchOne(Transacciones.TRANSACCIONES.ID, value);
	}

	/**
	 * Fetch records that have <code>fecha IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByFecha(Long... values) {
		return fetch(Transacciones.TRANSACCIONES.FECHA, values);
	}

	/**
	 * Fetch records that have <code>codigooper IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByCodigooper(String... values) {
		return fetch(Transacciones.TRANSACCIONES.CODIGOOPER, values);
	}

	/**
	 * Fetch records that have <code>procod IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByProcod(String... values) {
		return fetch(Transacciones.TRANSACCIONES.PROCOD, values);
	}

	/**
	 * Fetch records that have <code>descmenu IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByDescmenu(String... values) {
		return fetch(Transacciones.TRANSACCIONES.DESCMENU, values);
	}

	/**
	 * Fetch records that have <code>importe IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByImporte(String... values) {
		return fetch(Transacciones.TRANSACCIONES.IMPORTE, values);
	}

	/**
	 * Fetch records that have <code>moneda IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByMoneda(String... values) {
		return fetch(Transacciones.TRANSACCIONES.MONEDA, values);
	}

	/**
	 * Fetch records that have <code>importeorigen IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByImporteorigen(String... values) {
		return fetch(Transacciones.TRANSACCIONES.IMPORTEORIGEN, values);
	}

	/**
	 * Fetch records that have <code>fee IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByFee(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.FEE, values);
	}

	/**
	 * Fetch records that have <code>reflocal IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByReflocal(String... values) {
		return fetch(Transacciones.TRANSACCIONES.REFLOCAL, values);
	}

	/**
	 * Fetch records that have <code>stan IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByStan(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.STAN, values);
	}

	/**
	 * Fetch records that have <code>refremota IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByRefremota(String... values) {
		return fetch(Transacciones.TRANSACCIONES.REFREMOTA, values);
	}

	/**
	 * Fetch records that have <code>refcliente IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByRefcliente(String... values) {
		return fetch(Transacciones.TRANSACCIONES.REFCLIENTE, values);
	}

	/**
	 * Fetch records that have <code>descproducto IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByDescproducto(String... values) {
		return fetch(Transacciones.TRANSACCIONES.DESCPRODUCTO, values);
	}

	/**
	 * Fetch records that have <code>turno IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByTurno(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.TURNO, values);
	}

	/**
	 * Fetch records that have <code>contabilizar IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByContabilizar(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.CONTABILIZAR, values);
	}

	/**
	 * Fetch records that have <code>zincronizada IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByZincronizada(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.ZINCRONIZADA, values);
	}

	/**
	 * Fetch records that have <code>cuenta IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByCuenta(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.CUENTA, values);
	}

	/**
	 * Fetch records that have <code>dia IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByDia(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.DIA, values);
	}

	/**
	 * Fetch records that have <code>total IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByTotal(String... values) {
		return fetch(Transacciones.TRANSACCIONES.TOTAL, values);
	}

	/**
	 * Fetch records that have <code>cashback IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByCashback(Float... values) {
		return fetch(Transacciones.TRANSACCIONES.CASHBACK, values);
	}

	/**
	 * Fetch records that have <code>impuesto IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByImpuesto(Float... values) {
		return fetch(Transacciones.TRANSACCIONES.IMPUESTO, values);
	}

	/**
	 * Fetch records that have <code>propina IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByPropina(Float... values) {
		return fetch(Transacciones.TRANSACCIONES.PROPINA, values);
	}

	/**
	 * Fetch records that have <code>tipo_tarjeta IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByTipoTarjeta(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.TIPO_TARJETA, values);
	}

	/**
	 * Fetch records that have <code>medio_pago IN (values)</code>
	 */
	public List<sigma.dbgen.tables.pojos.Transacciones> fetchByMedioPago(Integer... values) {
		return fetch(Transacciones.TRANSACCIONES.MEDIO_PAGO, values);
	}
}
