/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import sigma.dbgen.DefaultSchema;
import sigma.dbgen.Keys;
import sigma.dbgen.tables.records.TransaccionDetalleRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionDetalle extends TableImpl<TransaccionDetalleRecord> {

	private static final long serialVersionUID = 1070750634;

	/**
	 * The reference instance of <code>transaccion_detalle</code>
	 */
	public static final TransaccionDetalle TRANSACCION_DETALLE = new TransaccionDetalle();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<TransaccionDetalleRecord> getRecordType() {
		return TransaccionDetalleRecord.class;
	}

	/**
	 * The column <code>transaccion_detalle.autorizacion_pt</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> AUTORIZACION_PT = createField("autorizacion_pt", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.cantidad</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> CANTIDAD = createField("cantidad", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.cantidad_promo</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> CANTIDAD_PROMO = createField("cantidad_promo", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.descuento</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> DESCUENTO = createField("descuento", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.fecha_actualizacion</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> FECHA_ACTUALIZACION = createField("fecha_actualizacion", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.id_campana</code>.
	 */
	public final TableField<TransaccionDetalleRecord, Integer> ID_CAMPANA = createField("id_campana", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>transaccion_detalle.id_producto</code>.
	 */
	public final TableField<TransaccionDetalleRecord, Integer> ID_PRODUCTO = createField("id_producto", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>transaccion_detalle.id_venta</code>.
	 */
	public final TableField<TransaccionDetalleRecord, Integer> ID_VENTA = createField("id_venta", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>transaccion_detalle.id_venta_detalle</code>.
	 */
	public final TableField<TransaccionDetalleRecord, Integer> ID_VENTA_DETALLE = createField("id_venta_detalle", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>transaccion_detalle.importe_compra</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> IMPORTE_COMPRA = createField("importe_compra", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.importe_venta</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> IMPORTE_VENTA = createField("importe_venta", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.is_premio</code>.
	 */
	public final TableField<TransaccionDetalleRecord, Integer> IS_PREMIO = createField("is_premio", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>transaccion_detalle.referencia</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> REFERENCIA = createField("referencia", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>transaccion_detalle.sobre_cargo</code>.
	 */
	public final TableField<TransaccionDetalleRecord, String> SOBRE_CARGO = createField("sobre_cargo", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * Create a <code>transaccion_detalle</code> table reference
	 */
	public TransaccionDetalle() {
		this("transaccion_detalle", null);
	}

	/**
	 * Create an aliased <code>transaccion_detalle</code> table reference
	 */
	public TransaccionDetalle(String alias) {
		this(alias, TRANSACCION_DETALLE);
	}

	private TransaccionDetalle(String alias, Table<TransaccionDetalleRecord> aliased) {
		this(alias, aliased, null);
	}

	private TransaccionDetalle(String alias, Table<TransaccionDetalleRecord> aliased, Field<?>[] parameters) {
		super(alias, DefaultSchema.DEFAULT_SCHEMA, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<TransaccionDetalleRecord, Integer> getIdentity() {
		return Keys.IDENTITY_TRANSACCION_DETALLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<TransaccionDetalleRecord> getPrimaryKey() {
		return Keys.PK_TRANSACCION_DETALLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<TransaccionDetalleRecord>> getKeys() {
		return Arrays.<UniqueKey<TransaccionDetalleRecord>>asList(Keys.PK_TRANSACCION_DETALLE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalle as(String alias) {
		return new TransaccionDetalle(alias, this);
	}

	/**
	 * Rename this table
	 */
	public TransaccionDetalle rename(String name) {
		return new TransaccionDetalle(name, null);
	}
}
