/**
 * This class is generated by jOOQ
 */
package sigma.dbgen;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import sigma.dbgen.tables.AndroidMetadata;
import sigma.dbgen.tables.CatalogoProductos;
import sigma.dbgen.tables.SqliteSequence;
import sigma.dbgen.tables.TransaccionDetalle;
import sigma.dbgen.tables.Transacciones;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

	private static final long serialVersionUID = -1597976648;

	/**
	 * The reference instance of <code></code>
	 */
	public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

	/**
	 * No further instances allowed
	 */
	private DefaultSchema() {
		super("");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			AndroidMetadata.ANDROID_METADATA,
			CatalogoProductos.CATALOGO_PRODUCTOS,
			SqliteSequence.SQLITE_SEQUENCE,
			TransaccionDetalle.TRANSACCION_DETALLE,
			Transacciones.TRANSACCIONES);
	}
}
