/**
 * This class is generated by jOOQ
 */
package sigma.dbgen;


import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import sigma.dbgen.tables.CatalogoProductos;
import sigma.dbgen.tables.TransaccionDetalle;
import sigma.dbgen.tables.Transacciones;
import sigma.dbgen.tables.records.CatalogoProductosRecord;
import sigma.dbgen.tables.records.TransaccionDetalleRecord;
import sigma.dbgen.tables.records.TransaccionesRecord;


/**
 * A class modelling foreign key relationships between tables of the <code></code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<CatalogoProductosRecord, Integer> IDENTITY_CATALOGO_PRODUCTOS = Identities0.IDENTITY_CATALOGO_PRODUCTOS;
	public static final Identity<TransaccionDetalleRecord, Integer> IDENTITY_TRANSACCION_DETALLE = Identities0.IDENTITY_TRANSACCION_DETALLE;
	public static final Identity<TransaccionesRecord, Integer> IDENTITY_TRANSACCIONES = Identities0.IDENTITY_TRANSACCIONES;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<CatalogoProductosRecord> PK_CATALOGO_PRODUCTOS = UniqueKeys0.PK_CATALOGO_PRODUCTOS;
	public static final UniqueKey<TransaccionDetalleRecord> PK_TRANSACCION_DETALLE = UniqueKeys0.PK_TRANSACCION_DETALLE;
	public static final UniqueKey<TransaccionesRecord> PK_TRANSACCIONES = UniqueKeys0.PK_TRANSACCIONES;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<CatalogoProductosRecord, Integer> IDENTITY_CATALOGO_PRODUCTOS = createIdentity(CatalogoProductos.CATALOGO_PRODUCTOS, CatalogoProductos.CATALOGO_PRODUCTOS.ID_PRODUCTO);
		public static Identity<TransaccionDetalleRecord, Integer> IDENTITY_TRANSACCION_DETALLE = createIdentity(TransaccionDetalle.TRANSACCION_DETALLE, TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA_DETALLE);
		public static Identity<TransaccionesRecord, Integer> IDENTITY_TRANSACCIONES = createIdentity(Transacciones.TRANSACCIONES, Transacciones.TRANSACCIONES.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<CatalogoProductosRecord> PK_CATALOGO_PRODUCTOS = createUniqueKey(CatalogoProductos.CATALOGO_PRODUCTOS, CatalogoProductos.CATALOGO_PRODUCTOS.ID_PRODUCTO);
		public static final UniqueKey<TransaccionDetalleRecord> PK_TRANSACCION_DETALLE = createUniqueKey(TransaccionDetalle.TRANSACCION_DETALLE, TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA_DETALLE);
		public static final UniqueKey<TransaccionesRecord> PK_TRANSACCIONES = createUniqueKey(Transacciones.TRANSACCIONES, Transacciones.TRANSACCIONES.ID);
	}
}
