/**
 * This class is generated by jOOQ
 */
package sigma.dbgen;


import javax.annotation.Generated;

import sigma.dbgen.tables.AndroidMetadata;
import sigma.dbgen.tables.CatalogoProductos;
import sigma.dbgen.tables.SqliteSequence;
import sigma.dbgen.tables.TransaccionDetalle;
import sigma.dbgen.tables.Transacciones;


/**
 * Convenience access to all tables in 
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table android_metadata
	 */
	public static final AndroidMetadata ANDROID_METADATA = AndroidMetadata.ANDROID_METADATA;

	/**
	 * The table catalogo_productos
	 */
	public static final CatalogoProductos CATALOGO_PRODUCTOS = CatalogoProductos.CATALOGO_PRODUCTOS;

	/**
	 * The table sqlite_sequence
	 */
	public static final SqliteSequence SQLITE_SEQUENCE = SqliteSequence.SQLITE_SEQUENCE;

	/**
	 * The table transaccion_detalle
	 */
	public static final TransaccionDetalle TRANSACCION_DETALLE = TransaccionDetalle.TRANSACCION_DETALLE;

	/**
	 * The table transacciones
	 */
	public static final Transacciones TRANSACCIONES = Transacciones.TRANSACCIONES;
}
