/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.records;


import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import sigma.dbgen.tables.Transacciones;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionesRecord extends UpdatableRecordImpl<TransaccionesRecord> {

	private static final long serialVersionUID = -1131504476;

	/**
	 * Setter for <code>transacciones.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>transacciones.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>transacciones.fecha</code>.
	 */
	public void setFecha(Long value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>transacciones.fecha</code>.
	 */
	public Long getFecha() {
		return (Long) getValue(1);
	}

	/**
	 * Setter for <code>transacciones.codigooper</code>.
	 */
	public void setCodigooper(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>transacciones.codigooper</code>.
	 */
	public String getCodigooper() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>transacciones.procod</code>.
	 */
	public void setProcod(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>transacciones.procod</code>.
	 */
	public String getProcod() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>transacciones.descmenu</code>.
	 */
	public void setDescmenu(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>transacciones.descmenu</code>.
	 */
	public String getDescmenu() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>transacciones.importe</code>.
	 */
	public void setImporte(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>transacciones.importe</code>.
	 */
	public String getImporte() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>transacciones.moneda</code>.
	 */
	public void setMoneda(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>transacciones.moneda</code>.
	 */
	public String getMoneda() {
		return (String) getValue(6);
	}

	/**
	 * Setter for <code>transacciones.importeorigen</code>.
	 */
	public void setImporteorigen(String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>transacciones.importeorigen</code>.
	 */
	public String getImporteorigen() {
		return (String) getValue(7);
	}

	/**
	 * Setter for <code>transacciones.fee</code>.
	 */
	public void setFee(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>transacciones.fee</code>.
	 */
	public Integer getFee() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>transacciones.reflocal</code>.
	 */
	public void setReflocal(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>transacciones.reflocal</code>.
	 */
	public String getReflocal() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>transacciones.stan</code>.
	 */
	public void setStan(Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>transacciones.stan</code>.
	 */
	public Integer getStan() {
		return (Integer) getValue(10);
	}

	/**
	 * Setter for <code>transacciones.refremota</code>.
	 */
	public void setRefremota(String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>transacciones.refremota</code>.
	 */
	public String getRefremota() {
		return (String) getValue(11);
	}

	/**
	 * Setter for <code>transacciones.refcliente</code>.
	 */
	public void setRefcliente(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>transacciones.refcliente</code>.
	 */
	public String getRefcliente() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>transacciones.descproducto</code>.
	 */
	public void setDescproducto(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>transacciones.descproducto</code>.
	 */
	public String getDescproducto() {
		return (String) getValue(13);
	}

	/**
	 * Setter for <code>transacciones.turno</code>.
	 */
	public void setTurno(Integer value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>transacciones.turno</code>.
	 */
	public Integer getTurno() {
		return (Integer) getValue(14);
	}

	/**
	 * Setter for <code>transacciones.contabilizar</code>.
	 */
	public void setContabilizar(Integer value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>transacciones.contabilizar</code>.
	 */
	public Integer getContabilizar() {
		return (Integer) getValue(15);
	}

	/**
	 * Setter for <code>transacciones.zincronizada</code>.
	 */
	public void setZincronizada(Integer value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>transacciones.zincronizada</code>.
	 */
	public Integer getZincronizada() {
		return (Integer) getValue(16);
	}

	/**
	 * Setter for <code>transacciones.cuenta</code>.
	 */
	public void setCuenta(Integer value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>transacciones.cuenta</code>.
	 */
	public Integer getCuenta() {
		return (Integer) getValue(17);
	}

	/**
	 * Setter for <code>transacciones.dia</code>.
	 */
	public void setDia(Integer value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>transacciones.dia</code>.
	 */
	public Integer getDia() {
		return (Integer) getValue(18);
	}

	/**
	 * Setter for <code>transacciones.total</code>.
	 */
	public void setTotal(String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>transacciones.total</code>.
	 */
	public String getTotal() {
		return (String) getValue(19);
	}

	/**
	 * Setter for <code>transacciones.cashback</code>.
	 */
	public void setCashback(Float value) {
		setValue(20, value);
	}

	/**
	 * Getter for <code>transacciones.cashback</code>.
	 */
	public Float getCashback() {
		return (Float) getValue(20);
	}

	/**
	 * Setter for <code>transacciones.impuesto</code>.
	 */
	public void setImpuesto(Float value) {
		setValue(21, value);
	}

	/**
	 * Getter for <code>transacciones.impuesto</code>.
	 */
	public Float getImpuesto() {
		return (Float) getValue(21);
	}

	/**
	 * Setter for <code>transacciones.propina</code>.
	 */
	public void setPropina(Float value) {
		setValue(22, value);
	}

	/**
	 * Getter for <code>transacciones.propina</code>.
	 */
	public Float getPropina() {
		return (Float) getValue(22);
	}

	/**
	 * Setter for <code>transacciones.tipo_tarjeta</code>.
	 */
	public void setTipoTarjeta(Integer value) {
		setValue(23, value);
	}

	/**
	 * Getter for <code>transacciones.tipo_tarjeta</code>.
	 */
	public Integer getTipoTarjeta() {
		return (Integer) getValue(23);
	}

	/**
	 * Setter for <code>transacciones.medio_pago</code>.
	 */
	public void setMedioPago(Integer value) {
		setValue(24, value);
	}

	/**
	 * Getter for <code>transacciones.medio_pago</code>.
	 */
	public Integer getMedioPago() {
		return (Integer) getValue(24);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TransaccionesRecord
	 */
	public TransaccionesRecord() {
		super(Transacciones.TRANSACCIONES);
	}

	/**
	 * Create a detached, initialised TransaccionesRecord
	 */
	public TransaccionesRecord(Integer id, Long fecha, String codigooper, String procod, String descmenu, String importe, String moneda, String importeorigen, Integer fee, String reflocal, Integer stan, String refremota, String refcliente, String descproducto, Integer turno, Integer contabilizar, Integer zincronizada, Integer cuenta, Integer dia, String total, Float cashback, Float impuesto, Float propina, Integer tipoTarjeta, Integer medioPago) {
		super(Transacciones.TRANSACCIONES);

		setValue(0, id);
		setValue(1, fecha);
		setValue(2, codigooper);
		setValue(3, procod);
		setValue(4, descmenu);
		setValue(5, importe);
		setValue(6, moneda);
		setValue(7, importeorigen);
		setValue(8, fee);
		setValue(9, reflocal);
		setValue(10, stan);
		setValue(11, refremota);
		setValue(12, refcliente);
		setValue(13, descproducto);
		setValue(14, turno);
		setValue(15, contabilizar);
		setValue(16, zincronizada);
		setValue(17, cuenta);
		setValue(18, dia);
		setValue(19, total);
		setValue(20, cashback);
		setValue(21, impuesto);
		setValue(22, propina);
		setValue(23, tipoTarjeta);
		setValue(24, medioPago);
	}
}
