/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

import sigma.dbgen.tables.TransaccionDetalle;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionDetalleRecord extends UpdatableRecordImpl<TransaccionDetalleRecord> implements Record14<String, String, String, String, String, Integer, Integer, Integer, Integer, String, String, Integer, String, String> {

	private static final long serialVersionUID = 581798305;

	/**
	 * Setter for <code>transaccion_detalle.autorizacion_pt</code>.
	 */
	public void setAutorizacionPt(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.autorizacion_pt</code>.
	 */
	public String getAutorizacionPt() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>transaccion_detalle.cantidad</code>.
	 */
	public void setCantidad(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.cantidad</code>.
	 */
	public String getCantidad() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>transaccion_detalle.cantidad_promo</code>.
	 */
	public void setCantidadPromo(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.cantidad_promo</code>.
	 */
	public String getCantidadPromo() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>transaccion_detalle.descuento</code>.
	 */
	public void setDescuento(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.descuento</code>.
	 */
	public String getDescuento() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>transaccion_detalle.fecha_actualizacion</code>.
	 */
	public void setFechaActualizacion(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.fecha_actualizacion</code>.
	 */
	public String getFechaActualizacion() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>transaccion_detalle.id_campana</code>.
	 */
	public void setIdCampana(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.id_campana</code>.
	 */
	public Integer getIdCampana() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>transaccion_detalle.id_producto</code>.
	 */
	public void setIdProducto(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.id_producto</code>.
	 */
	public Integer getIdProducto() {
		return (Integer) getValue(6);
	}

	/**
	 * Setter for <code>transaccion_detalle.id_venta</code>.
	 */
	public void setIdVenta(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.id_venta</code>.
	 */
	public Integer getIdVenta() {
		return (Integer) getValue(7);
	}

	/**
	 * Setter for <code>transaccion_detalle.id_venta_detalle</code>.
	 */
	public void setIdVentaDetalle(Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.id_venta_detalle</code>.
	 */
	public Integer getIdVentaDetalle() {
		return (Integer) getValue(8);
	}

	/**
	 * Setter for <code>transaccion_detalle.importe_compra</code>.
	 */
	public void setImporteCompra(String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.importe_compra</code>.
	 */
	public String getImporteCompra() {
		return (String) getValue(9);
	}

	/**
	 * Setter for <code>transaccion_detalle.importe_venta</code>.
	 */
	public void setImporteVenta(String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.importe_venta</code>.
	 */
	public String getImporteVenta() {
		return (String) getValue(10);
	}

	/**
	 * Setter for <code>transaccion_detalle.is_premio</code>.
	 */
	public void setIsPremio(Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.is_premio</code>.
	 */
	public Integer getIsPremio() {
		return (Integer) getValue(11);
	}

	/**
	 * Setter for <code>transaccion_detalle.referencia</code>.
	 */
	public void setReferencia(String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.referencia</code>.
	 */
	public String getReferencia() {
		return (String) getValue(12);
	}

	/**
	 * Setter for <code>transaccion_detalle.sobre_cargo</code>.
	 */
	public void setSobreCargo(String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>transaccion_detalle.sobre_cargo</code>.
	 */
	public String getSobreCargo() {
		return (String) getValue(13);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record14 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, Integer, Integer, Integer, Integer, String, String, Integer, String, String> fieldsRow() {
		return (Row14) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row14<String, String, String, String, String, Integer, Integer, Integer, Integer, String, String, Integer, String, String> valuesRow() {
		return (Row14) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return TransaccionDetalle.TRANSACCION_DETALLE.AUTORIZACION_PT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return TransaccionDetalle.TRANSACCION_DETALLE.CANTIDAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return TransaccionDetalle.TRANSACCION_DETALLE.CANTIDAD_PROMO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return TransaccionDetalle.TRANSACCION_DETALLE.DESCUENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return TransaccionDetalle.TRANSACCION_DETALLE.FECHA_ACTUALIZACION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return TransaccionDetalle.TRANSACCION_DETALLE.ID_CAMPANA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return TransaccionDetalle.TRANSACCION_DETALLE.ID_PRODUCTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field9() {
		return TransaccionDetalle.TRANSACCION_DETALLE.ID_VENTA_DETALLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field10() {
		return TransaccionDetalle.TRANSACCION_DETALLE.IMPORTE_COMPRA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field11() {
		return TransaccionDetalle.TRANSACCION_DETALLE.IMPORTE_VENTA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field12() {
		return TransaccionDetalle.TRANSACCION_DETALLE.IS_PREMIO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field13() {
		return TransaccionDetalle.TRANSACCION_DETALLE.REFERENCIA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field14() {
		return TransaccionDetalle.TRANSACCION_DETALLE.SOBRE_CARGO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getAutorizacionPt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getCantidad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getCantidadPromo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getDescuento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getFechaActualizacion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getIdCampana();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getIdProducto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getIdVenta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value9() {
		return getIdVentaDetalle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value10() {
		return getImporteCompra();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value11() {
		return getImporteVenta();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value12() {
		return getIsPremio();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value13() {
		return getReferencia();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value14() {
		return getSobreCargo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value1(String value) {
		setAutorizacionPt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value2(String value) {
		setCantidad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value3(String value) {
		setCantidadPromo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value4(String value) {
		setDescuento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value5(String value) {
		setFechaActualizacion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value6(Integer value) {
		setIdCampana(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value7(Integer value) {
		setIdProducto(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value8(Integer value) {
		setIdVenta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value9(Integer value) {
		setIdVentaDetalle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value10(String value) {
		setImporteCompra(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value11(String value) {
		setImporteVenta(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value12(Integer value) {
		setIsPremio(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value13(String value) {
		setReferencia(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord value14(String value) {
		setSobreCargo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TransaccionDetalleRecord values(String value1, String value2, String value3, String value4, String value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, String value11, Integer value12, String value13, String value14) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		value10(value10);
		value11(value11);
		value12(value12);
		value13(value13);
		value14(value14);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TransaccionDetalleRecord
	 */
	public TransaccionDetalleRecord() {
		super(TransaccionDetalle.TRANSACCION_DETALLE);
	}

	/**
	 * Create a detached, initialised TransaccionDetalleRecord
	 */
	public TransaccionDetalleRecord(String autorizacionPt, String cantidad, String cantidadPromo, String descuento, String fechaActualizacion, Integer idCampana, Integer idProducto, Integer idVenta, Integer idVentaDetalle, String importeCompra, String importeVenta, Integer isPremio, String referencia, String sobreCargo) {
		super(TransaccionDetalle.TRANSACCION_DETALLE);

		setValue(0, autorizacionPt);
		setValue(1, cantidad);
		setValue(2, cantidadPromo);
		setValue(3, descuento);
		setValue(4, fechaActualizacion);
		setValue(5, idCampana);
		setValue(6, idProducto);
		setValue(7, idVenta);
		setValue(8, idVentaDetalle);
		setValue(9, importeCompra);
		setValue(10, importeVenta);
		setValue(11, isPremio);
		setValue(12, referencia);
		setValue(13, sobreCargo);
	}
}
