/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AndroidMetadata implements Serializable {

	private static final long serialVersionUID = -1468438791;

	private String locale;

	public AndroidMetadata() {}

	public AndroidMetadata(AndroidMetadata value) {
		this.locale = value.locale;
	}

	public AndroidMetadata(
		String locale
	) {
		this.locale = locale;
	}

	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}
}
