/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CatalogoProductos implements Serializable {

	private static final long serialVersionUID = 92750546;

	private String  descripcion;
	private String  desviacion;
	private String  existencia;
	private String  fechaSync;
	private Integer idCategoria;
	private Integer idMarca;
	private Integer idProducto;
	private Integer idTipoProducto;
	private Integer idUnidad;
	private Integer minimo;
	private String  precioCompra;
	private String  precioVenta;
	private String  precioVentaMayoreo;
	private String  promedio;
	private String  sku;
	private String  sugerido;
	private Integer sync;
	private String  techo;
	private String  totalVentas;
	private Integer dbState;
	private String  imagePreview;
	private String  logo;
	private Integer custom;

	public CatalogoProductos() {}

	public CatalogoProductos(CatalogoProductos value) {
		this.descripcion = value.descripcion;
		this.desviacion = value.desviacion;
		this.existencia = value.existencia;
		this.fechaSync = value.fechaSync;
		this.idCategoria = value.idCategoria;
		this.idMarca = value.idMarca;
		this.idProducto = value.idProducto;
		this.idTipoProducto = value.idTipoProducto;
		this.idUnidad = value.idUnidad;
		this.minimo = value.minimo;
		this.precioCompra = value.precioCompra;
		this.precioVenta = value.precioVenta;
		this.precioVentaMayoreo = value.precioVentaMayoreo;
		this.promedio = value.promedio;
		this.sku = value.sku;
		this.sugerido = value.sugerido;
		this.sync = value.sync;
		this.techo = value.techo;
		this.totalVentas = value.totalVentas;
		this.dbState = value.dbState;
		this.imagePreview = value.imagePreview;
		this.logo = value.logo;
		this.custom = value.custom;
	}

	public CatalogoProductos(
		String  descripcion,
		String  desviacion,
		String  existencia,
		String  fechaSync,
		Integer idCategoria,
		Integer idMarca,
		Integer idProducto,
		Integer idTipoProducto,
		Integer idUnidad,
		Integer minimo,
		String  precioCompra,
		String  precioVenta,
		String  precioVentaMayoreo,
		String  promedio,
		String  sku,
		String  sugerido,
		Integer sync,
		String  techo,
		String  totalVentas,
		Integer dbState,
		String  imagePreview,
		String  logo,
		Integer custom
	) {
		this.descripcion = descripcion;
		this.desviacion = desviacion;
		this.existencia = existencia;
		this.fechaSync = fechaSync;
		this.idCategoria = idCategoria;
		this.idMarca = idMarca;
		this.idProducto = idProducto;
		this.idTipoProducto = idTipoProducto;
		this.idUnidad = idUnidad;
		this.minimo = minimo;
		this.precioCompra = precioCompra;
		this.precioVenta = precioVenta;
		this.precioVentaMayoreo = precioVentaMayoreo;
		this.promedio = promedio;
		this.sku = sku;
		this.sugerido = sugerido;
		this.sync = sync;
		this.techo = techo;
		this.totalVentas = totalVentas;
		this.dbState = dbState;
		this.imagePreview = imagePreview;
		this.logo = logo;
		this.custom = custom;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getDesviacion() {
		return this.desviacion;
	}

	public void setDesviacion(String desviacion) {
		this.desviacion = desviacion;
	}

	public String getExistencia() {
		return this.existencia;
	}

	public void setExistencia(String existencia) {
		this.existencia = existencia;
	}

	public String getFechaSync() {
		return this.fechaSync;
	}

	public void setFechaSync(String fechaSync) {
		this.fechaSync = fechaSync;
	}

	public Integer getIdCategoria() {
		return this.idCategoria;
	}

	public void setIdCategoria(Integer idCategoria) {
		this.idCategoria = idCategoria;
	}

	public Integer getIdMarca() {
		return this.idMarca;
	}

	public void setIdMarca(Integer idMarca) {
		this.idMarca = idMarca;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Integer getIdTipoProducto() {
		return this.idTipoProducto;
	}

	public void setIdTipoProducto(Integer idTipoProducto) {
		this.idTipoProducto = idTipoProducto;
	}

	public Integer getIdUnidad() {
		return this.idUnidad;
	}

	public void setIdUnidad(Integer idUnidad) {
		this.idUnidad = idUnidad;
	}

	public Integer getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Integer minimo) {
		this.minimo = minimo;
	}

	public String getPrecioCompra() {
		return this.precioCompra;
	}

	public void setPrecioCompra(String precioCompra) {
		this.precioCompra = precioCompra;
	}

	public String getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(String precioVenta) {
		this.precioVenta = precioVenta;
	}

	public String getPrecioVentaMayoreo() {
		return this.precioVentaMayoreo;
	}

	public void setPrecioVentaMayoreo(String precioVentaMayoreo) {
		this.precioVentaMayoreo = precioVentaMayoreo;
	}

	public String getPromedio() {
		return this.promedio;
	}

	public void setPromedio(String promedio) {
		this.promedio = promedio;
	}

	public String getSku() {
		return this.sku;
	}

	public void setSku(String sku) {
		this.sku = sku;
	}

	public String getSugerido() {
		return this.sugerido;
	}

	public void setSugerido(String sugerido) {
		this.sugerido = sugerido;
	}

	public Integer getSync() {
		return this.sync;
	}

	public void setSync(Integer sync) {
		this.sync = sync;
	}

	public String getTecho() {
		return this.techo;
	}

	public void setTecho(String techo) {
		this.techo = techo;
	}

	public String getTotalVentas() {
		return this.totalVentas;
	}

	public void setTotalVentas(String totalVentas) {
		this.totalVentas = totalVentas;
	}

	public Integer getDbState() {
		return this.dbState;
	}

	public void setDbState(Integer dbState) {
		this.dbState = dbState;
	}

	public String getImagePreview() {
		return this.imagePreview;
	}

	public void setImagePreview(String imagePreview) {
		this.imagePreview = imagePreview;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public Integer getCustom() {
		return this.custom;
	}

	public void setCustom(Integer custom) {
		this.custom = custom;
	}
}
