/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transacciones implements Serializable {

	private static final long serialVersionUID = 153460552;

	private Integer id;
	private Long    fecha;
	private String  codigooper;
	private String  procod;
	private String  descmenu;
	private String  importe;
	private String  moneda;
	private String  importeorigen;
	private Integer fee;
	private String  reflocal;
	private Integer stan;
	private String  refremota;
	private String  refcliente;
	private String  descproducto;
	private Integer turno;
	private Integer contabilizar;
	private Integer zincronizada;
	private Integer cuenta;
	private Integer dia;
	private String  total;
	private Float   cashback;
	private Float   impuesto;
	private Float   propina;
	private Integer tipoTarjeta;
	private Integer medioPago;

	public Transacciones() {}

	public Transacciones(Transacciones value) {
		this.id = value.id;
		this.fecha = value.fecha;
		this.codigooper = value.codigooper;
		this.procod = value.procod;
		this.descmenu = value.descmenu;
		this.importe = value.importe;
		this.moneda = value.moneda;
		this.importeorigen = value.importeorigen;
		this.fee = value.fee;
		this.reflocal = value.reflocal;
		this.stan = value.stan;
		this.refremota = value.refremota;
		this.refcliente = value.refcliente;
		this.descproducto = value.descproducto;
		this.turno = value.turno;
		this.contabilizar = value.contabilizar;
		this.zincronizada = value.zincronizada;
		this.cuenta = value.cuenta;
		this.dia = value.dia;
		this.total = value.total;
		this.cashback = value.cashback;
		this.impuesto = value.impuesto;
		this.propina = value.propina;
		this.tipoTarjeta = value.tipoTarjeta;
		this.medioPago = value.medioPago;
	}

	public Transacciones(
		Integer id,
		Long    fecha,
		String  codigooper,
		String  procod,
		String  descmenu,
		String  importe,
		String  moneda,
		String  importeorigen,
		Integer fee,
		String  reflocal,
		Integer stan,
		String  refremota,
		String  refcliente,
		String  descproducto,
		Integer turno,
		Integer contabilizar,
		Integer zincronizada,
		Integer cuenta,
		Integer dia,
		String  total,
		Float   cashback,
		Float   impuesto,
		Float   propina,
		Integer tipoTarjeta,
		Integer medioPago
	) {
		this.id = id;
		this.fecha = fecha;
		this.codigooper = codigooper;
		this.procod = procod;
		this.descmenu = descmenu;
		this.importe = importe;
		this.moneda = moneda;
		this.importeorigen = importeorigen;
		this.fee = fee;
		this.reflocal = reflocal;
		this.stan = stan;
		this.refremota = refremota;
		this.refcliente = refcliente;
		this.descproducto = descproducto;
		this.turno = turno;
		this.contabilizar = contabilizar;
		this.zincronizada = zincronizada;
		this.cuenta = cuenta;
		this.dia = dia;
		this.total = total;
		this.cashback = cashback;
		this.impuesto = impuesto;
		this.propina = propina;
		this.tipoTarjeta = tipoTarjeta;
		this.medioPago = medioPago;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Long getFecha() {
		return this.fecha;
	}

	public void setFecha(Long fecha) {
		this.fecha = fecha;
	}

	public String getCodigooper() {
		return this.codigooper;
	}

	public void setCodigooper(String codigooper) {
		this.codigooper = codigooper;
	}

	public String getProcod() {
		return this.procod;
	}

	public void setProcod(String procod) {
		this.procod = procod;
	}

	public String getDescmenu() {
		return this.descmenu;
	}

	public void setDescmenu(String descmenu) {
		this.descmenu = descmenu;
	}

	public String getImporte() {
		return this.importe;
	}

	public void setImporte(String importe) {
		this.importe = importe;
	}

	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	public String getImporteorigen() {
		return this.importeorigen;
	}

	public void setImporteorigen(String importeorigen) {
		this.importeorigen = importeorigen;
	}

	public Integer getFee() {
		return this.fee;
	}

	public void setFee(Integer fee) {
		this.fee = fee;
	}

	public String getReflocal() {
		return this.reflocal;
	}

	public void setReflocal(String reflocal) {
		this.reflocal = reflocal;
	}

	public Integer getStan() {
		return this.stan;
	}

	public void setStan(Integer stan) {
		this.stan = stan;
	}

	public String getRefremota() {
		return this.refremota;
	}

	public void setRefremota(String refremota) {
		this.refremota = refremota;
	}

	public String getRefcliente() {
		return this.refcliente;
	}

	public void setRefcliente(String refcliente) {
		this.refcliente = refcliente;
	}

	public String getDescproducto() {
		return this.descproducto;
	}

	public void setDescproducto(String descproducto) {
		this.descproducto = descproducto;
	}

	public Integer getTurno() {
		return this.turno;
	}

	public void setTurno(Integer turno) {
		this.turno = turno;
	}

	public Integer getContabilizar() {
		return this.contabilizar;
	}

	public void setContabilizar(Integer contabilizar) {
		this.contabilizar = contabilizar;
	}

	public Integer getZincronizada() {
		return this.zincronizada;
	}

	public void setZincronizada(Integer zincronizada) {
		this.zincronizada = zincronizada;
	}

	public Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(Integer cuenta) {
		this.cuenta = cuenta;
	}

	public Integer getDia() {
		return this.dia;
	}

	public void setDia(Integer dia) {
		this.dia = dia;
	}

	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public Float getCashback() {
		return this.cashback;
	}

	public void setCashback(Float cashback) {
		this.cashback = cashback;
	}

	public Float getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(Float impuesto) {
		this.impuesto = impuesto;
	}

	public Float getPropina() {
		return this.propina;
	}

	public void setPropina(Float propina) {
		this.propina = propina;
	}

	public Integer getTipoTarjeta() {
		return this.tipoTarjeta;
	}

	public void setTipoTarjeta(Integer tipoTarjeta) {
		this.tipoTarjeta = tipoTarjeta;
	}

	public Integer getMedioPago() {
		return this.medioPago;
	}

	public void setMedioPago(Integer medioPago) {
		this.medioPago = medioPago;
	}
}
