/**
 * This class is generated by jOOQ
 */
package sigma.dbgen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.4"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TransaccionDetalle implements Serializable {

	private static final long serialVersionUID = 1557998918;

	private String  autorizacionPt;
	private String  cantidad;
	private String  cantidadPromo;
	private String  descuento;
	private String  fechaActualizacion;
	private Integer idCampana;
	private Integer idProducto;
	private Integer idVenta;
	private Integer idVentaDetalle;
	private String  importeCompra;
	private String  importeVenta;
	private Integer isPremio;
	private String  referencia;
	private String  sobreCargo;

	public TransaccionDetalle() {}

	public TransaccionDetalle(TransaccionDetalle value) {
		this.autorizacionPt = value.autorizacionPt;
		this.cantidad = value.cantidad;
		this.cantidadPromo = value.cantidadPromo;
		this.descuento = value.descuento;
		this.fechaActualizacion = value.fechaActualizacion;
		this.idCampana = value.idCampana;
		this.idProducto = value.idProducto;
		this.idVenta = value.idVenta;
		this.idVentaDetalle = value.idVentaDetalle;
		this.importeCompra = value.importeCompra;
		this.importeVenta = value.importeVenta;
		this.isPremio = value.isPremio;
		this.referencia = value.referencia;
		this.sobreCargo = value.sobreCargo;
	}

	public TransaccionDetalle(
		String  autorizacionPt,
		String  cantidad,
		String  cantidadPromo,
		String  descuento,
		String  fechaActualizacion,
		Integer idCampana,
		Integer idProducto,
		Integer idVenta,
		Integer idVentaDetalle,
		String  importeCompra,
		String  importeVenta,
		Integer isPremio,
		String  referencia,
		String  sobreCargo
	) {
		this.autorizacionPt = autorizacionPt;
		this.cantidad = cantidad;
		this.cantidadPromo = cantidadPromo;
		this.descuento = descuento;
		this.fechaActualizacion = fechaActualizacion;
		this.idCampana = idCampana;
		this.idProducto = idProducto;
		this.idVenta = idVenta;
		this.idVentaDetalle = idVentaDetalle;
		this.importeCompra = importeCompra;
		this.importeVenta = importeVenta;
		this.isPremio = isPremio;
		this.referencia = referencia;
		this.sobreCargo = sobreCargo;
	}

	public String getAutorizacionPt() {
		return this.autorizacionPt;
	}

	public void setAutorizacionPt(String autorizacionPt) {
		this.autorizacionPt = autorizacionPt;
	}

	public String getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(String cantidad) {
		this.cantidad = cantidad;
	}

	public String getCantidadPromo() {
		return this.cantidadPromo;
	}

	public void setCantidadPromo(String cantidadPromo) {
		this.cantidadPromo = cantidadPromo;
	}

	public String getDescuento() {
		return this.descuento;
	}

	public void setDescuento(String descuento) {
		this.descuento = descuento;
	}

	public String getFechaActualizacion() {
		return this.fechaActualizacion;
	}

	public void setFechaActualizacion(String fechaActualizacion) {
		this.fechaActualizacion = fechaActualizacion;
	}

	public Integer getIdCampana() {
		return this.idCampana;
	}

	public void setIdCampana(Integer idCampana) {
		this.idCampana = idCampana;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public Integer getIdVenta() {
		return this.idVenta;
	}

	public void setIdVenta(Integer idVenta) {
		this.idVenta = idVenta;
	}

	public Integer getIdVentaDetalle() {
		return this.idVentaDetalle;
	}

	public void setIdVentaDetalle(Integer idVentaDetalle) {
		this.idVentaDetalle = idVentaDetalle;
	}

	public String getImporteCompra() {
		return this.importeCompra;
	}

	public void setImporteCompra(String importeCompra) {
		this.importeCompra = importeCompra;
	}

	public String getImporteVenta() {
		return this.importeVenta;
	}

	public void setImporteVenta(String importeVenta) {
		this.importeVenta = importeVenta;
	}

	public Integer getIsPremio() {
		return this.isPremio;
	}

	public void setIsPremio(Integer isPremio) {
		this.isPremio = isPremio;
	}

	public String getReferencia() {
		return this.referencia;
	}

	public void setReferencia(String referencia) {
		this.referencia = referencia;
	}

	public String getSobreCargo() {
		return this.sobreCargo;
	}

	public void setSobreCargo(String sobreCargo) {
		this.sobreCargo = sobreCargo;
	}
}
